#!/usr/bin/env node

const Eth = require('ethjs')
const Deployer = require('./app/deployer.js')
const Wallet = require('./app/wallet.js')
const Utils = require('./app/utils.js')
const abi = require('ethereumjs-abi')


if (process.argv.length < 3) {
  console.error('Usage: ./transfer_owner <owned address> <recipient address>')
  process.exit(1)
}

const owned = process.argv[2]
const recipient = process.argv[3]

const providerUrl = process.env['ETH_HTTP_URL'] || 'http://localhost:18545'
const utils = Utils(new Eth.HttpProvider(providerUrl))
const privateKey = process.env['PRIVATE_KEY'] || '4d6cf3ce1ac71e79aa33cf481dedf2e73acb548b1294a70447c960784302d2fb'
const wallet = Wallet(privateKey, utils)

const funcSelector = "0xf2fde38b" // "transferOwnership(address)"
const encoded = abi.rawEncode(['address'], [recipient])

wallet.send({
  to: owned,
  data: (funcSelector + encoded.toString('hex')),
})
.then(utils.getTxReceipt)
.then(receipt => {
  console.log(receipt)
  if (receipt.logs.length) {
    console.log(`ownership of ${owned} transferred to ${recipient}`)
  } else {
    console.log("FAILED!!!")
  }
})
